version: "3.3"
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
  app:
    environment:
      API_ENV: ""
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: credify-test/app:latest
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
