version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: credify-test/app:latest
    ports:
      - '8081:8081'
    stdin_open: true
    tty: true
