version: "3.3"
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
  backend:
    build: ./backend
    image: credify-test/backend:latest
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - '8081:8081'
    stdin_open: true
    tty: true
    depends_on:
      - postgres
